name: detoxa
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  stacked: 2.2.1
  get_it: ^7.2.0
  injectable: ^1.5.3
  dio: ^4.0.0
  shared_preferences: ^2.0.7
  cached_network_image: ^3.1.0
  flutter_swiper: ^1.1.6
  intl: ^0.17.0
  auto_size_text: ^2.1.0
  # firebase_crashlytics: 2.2.1
  # firebase_analytics: 8.3.2
  # firebase_messaging: 10.0.7
  fluttertoast: ^8.0.8
  url_launcher: ^6.0.18
  share_plus: ^3.0.4
  image_picker: ^0.8.4+4
  image_cropper: ^1.4.1
  pin_code_fields: ^7.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  injectable_generator: ^1.5.3
    
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets: 
    - assets/images/
    - assets/images/trackers/hand&eye_tracker/
    
  
